version: '3'
services:
  app:
    image: electric-vehicle-charging-station-management-image
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "2022:2022"
    environment:
      - DB_URL=jdbc:postgresql://dbpostgresql:5432/evcsm_db
      - DB_USER=postgres
      - DB_PASS=password
    depends_on:
      - dbpostgresql
#      dbpostgresql:
#        condition: service_healthy
  dbpostgresql:
    build:
      context: .
      dockerfile: PostgresDockerfile
    image: postgres
    container_name: postgresql-container
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: evcsm_db
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d
