version: '3.8'

services:
  app:
    image: behrooz2022/gis-project
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "2022:2022"
    environment:
      - DB_URL=jdbc:postgresql://dbpostgresql:5432/evcsm_db
      - DB_USER=postgres
      - DB_PASS=password
    depends_on:
      - dbpostgresql
  dbpostgresql:
    build:
      context: .
      dockerfile: PostgresDockerfile
    image: postgres-gis
    container_name: postgres-gis-container
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: evcsm_db
    volumes:
      - ./db/schema.sql:/docker-entrypoint-initdb.d/postgres-gis-container.sh
