version: '3.1'
services:
  app:
    container_name: electric-vehicle-charging-station-management-container
    image: electric-vehicle-charging-station-management-image
    build: ./
    ports:
      - "2022:2022"
    depends_on:
      - dbpostgresql
  dbpostgresql:
    image: postgres
    container_name: postgresql-container
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=evcsm_db