version: '3'
services:
  app:
    image: electric-vehicle-charging-station-management-image
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "2022:2022"
    environment:
      - DB_URL=jdbc:postgresql://dbpostgresql:5432/evcsm_db
      - B_USER=postgres
      - DB_PASS=root
    depends_on:
      dbpostgresql:
        condition: service_healthy
  dbpostgresql:
    image: postgres
    container_name: postgresql-container
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=evcsm_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5