server:
  port: 2022
  error:
    include-message: always
    include-binding-errors: always
# Spring Boot configuration
spring:
  application.name: electric-vehicle-charging-station-management
  application.version: @project.version@
  liquibase.change-log: "classpath:/db/changelog/master.xml"
  queries:
    users-query: select user_name, password, active_flag from tbl_user where user_name=?
    roles-query: select u.user_name, r.role from tbl_user u inner join tbl_user_role ur on (u.id=ur.user_id) inner join tbl_role r on (ur.role_id=r.id) where u.user_name=?
  tomcat:
    uri-encoding: UTF-8
  messages:
    basename: i18n.messages
    encoding: UTF-8
  thymeleaf:
    cache: false
    encoding: UTF-8
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/evcsm_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: false
  sql:
    init:
      mode: always