server.port: 2022

# Spring Boot configuration
spring:
  application.name: electric-vehicle-charging-station-management
  liquibase.change-log: "classpath:/db/changelog/master.xml"
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/evcsm_db
    username: postgres
    password: root
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true