apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: gis-project
  name: gis-project
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gis-project
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gis-project
    spec:
      containers:
        - image: behrooz2022/gis-project
          name: electric-vehicle-charging-station-management-image
          resources: {}
          imagePullPolicy: IfNotPresent
          env:
          - name: DB_URL
            value: jdbc:postgresql://postgres-db/evcsm_db
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: username
          - name: DB_PASS
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: password
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: gis-project
  name: gis-project
spec:
  ports:
    - name: 80-2022
      port: 80
      protocol: TCP
      targetPort: 2022
  selector:
    app: gis-project
  type: LoadBalancer
status:
  loadBalancer: {}